export const FETCH_SURAH_LISTE = "FETCH_SURAH_LISTE"
export const FETCH_SURAH_LISTE_SUCCESS = "FETCH_SURAH_LISTE_SUCCESS"
export const FETCH_SURAH_LISTE_FAILURE = "FETCH_SURAH_LISTE_FAILURE"

export const FETCH_SURAH = "FETCH_SURAH"
export const FETCH_SURAH_SUCCESS = "FETCH_SURAH_SUCCESS"
export const FETCH_SURAH_FAILURE = "FETCH_SURAH_FAILURE"

export const FETCH_EDITION = "FETCH_EDITION"
export const FETCH_EDITION_SUCCESS = "FETCH_EDITION_SUCCESS"
export const FETCH_EDITION_FAILURE = "FETCH_EDITION_FAILURE"

export const CHANGE_SURAH = "CHANGE_SURAH"
export const CHANGE_EDITION = "CHANGE_EDITION"

export const FETCH_TAFSIR = "FETCH_TAFSIR"
export const FETCH_TAFSIR_SUCCESS = "FETCH_TAFSIR_SUCCESS"
export const FETCH_TAFSIR_FAILURE = "FETCH_TAFSIR_FAILURE"

export const PLAY_SURAH = "PLAY_SURAH"
export const PAUSE_SURAH = "PAUSE_SURAH"

export const TOGGLE_ARABE = "TOGGLE_ARABE"
export const TOGGLE_FRANCAIS = "TOGGLE_FRANCAIS"
export const TOGGLE_PHONETIQUE = "TOGGLE_PHONETIQUE"